# Dependencies
highlighter:         rouge
plugins:             [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           blog/:title/

# Setup
title:               internaught.io
tagline:             'A blog of questionable meaning...'
description:         'Just some blog for Scott to keep his trials and tribulations on file in case they ever prove useful.'
paginate:            10

# About/contact
author:
  name:              Internaught Scott
  url:               https://twitter.com/ScottaBeTrue
  email:             scott@internaught.io

# Custom vars
version:             0.0.2
