# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               internaught.io
tagline:             'A blog of sorts...'
description:         'Just some blog for Scott to keep his trials and tribulations on file in case they ever prove useful.'
url:                 http://internaught.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Internaught Scott
  url:               https://twitter.com/ScottaBeTrue
  email:             scott@internaught.io

# Custom vars
version:             0.0.1
